### ISSUE TITLE
"drag and drop the zip" should have screenshot

### ISSUE THREAD

**Issue by AkihiroSuda** [dockersamples/101-tutorial#10]
https://github.com/dockersamples/101-tutorial/blob/master/docs_en/tutorial/our-application/index.md#getting-our-app-into-pwd

> As a tip, you can drag and drop the zip (or any other file) on to the terminal in PWD.

In Docker Meetup Tokyo, this was hard for a lot of attendees.
Adding screenshot would be helpful.

**Comment by mikesir87** [comment]
Thanks @AkihiroSuda and I apologize for the delay in responding. Yes... this is certainly something we should be able to do fairly quickly. Thanks for the input/feedback!
