### ISSUE TITLE
Incorrect link to pwd-tips in Using Docker Compose

### ISSUE THREAD

**Issue by ridono** [dockersamples/101-tutorial#16]
The link `create a file` to the pwd-tips page does not work in the section [Creating our Compose File](https://github.com/dockersamples/101-tutorial/blob/master/docs_en/tutorial/using-docker-compose/index.md#creating-our-compose-file).

The link points to 
`/pwd-tips.md#creating-files`
but should point to
`/pwd-tips#creating-files`

**Comment by mikesir87** [comment]
Good catch! Feel free to make a PR to fix it. Would be a nice and easy contribution! If you need some pointers, just let us know!
