### ISSUE TITLE
Docker-101: Tutorial - docker/getting-started:pwd started but URL not openning

### ISSUE THREAD

**Issue by KaushikPathak90** [dockersamples/101-tutorial#27]
![1](https://user-images.githubusercontent.com/45171300/88772397-59367300-d19e-11ea-9249-8a3e877abcb3.png)

After Waiting for http://ip172-18-0-63-bsgi06boudsg00bqlvf0-80.direct.labs.play-with-docker.com/
Finally 
http://ip172-18-0-63-bsgi06boudsg00bqlvf0-80.direct.labs.play-with-docker.com/
Says
This page isn’t working
ip172-18-0-63-bsgi06boudsg00bqlvf0-80.direct.labs.play-with-docker.com didn’t send any data.
ERR_EMPTY_RESPONSE

Was working 26th July 2020.

**Comment by KaushikPathak90** [comment]
Checked now..
Ok.
If no body worked on this then issue can be closed.

**Comment by Shocking-Sys** [comment]
It's container on "shared" server, of course i sure they don't give you 4GB instance, here 10+ more folks who "Try docker" at same moment so it's a normal behavior that's it's not available instantly for you - wait a little bit and try load it again. If you want workload without problems try it on your own PC (localhost) or rent VDS and try it like in prod workflow.
You can close Issues. Yeah.

**Comment by KaushikPathak90** [comment]
Oh. Sorry. I didn't know there was capacity issues.
Surely will try installing in my PC.
Thanks.
