### ISSUE TITLE
build path ..\101-tutorial\docs either does not exist, is not accessible, or is not a valid URL.

### ISSUE THREAD

**Issue by zygimantus** [dockersamples/101-tutorial#6]
Running `docker-compose up` gives an error build path ..\101-tutorial\docs either does not exist, is not accessible, or is not a valid URL. What I am doing wrong?

**Comment by mikesir87** [comment]
Ah! Good catch. We did some rearranging of the projects and that instruction wasn't updated. The path needs to be mounting `docs_en`. We'll update the instructions!

**Comment by mikesir87** [comment]
Ok. That wasn't 100% true. We need to update the mkdocs config to look for a different directory for the docs folder. Working on that now!

**Comment by mikesir87** [comment]
Ok. Just pushed some changes to help resolve this. Feel free to check out the README. Note that you will need to rebuild the image being used for docker-compose (`docker-compose up --build`).

**Comment by zygimantus** [comment]
Yep, now it woks, thank you.
